"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react"
import { Code2, Users, Target, Lightbulb } from "lucide-react"

type Language = "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  translations: typeof translations.en
}

export const translations = {
  en: {
    // Navigation
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      experience: "Experience",
      certifications: "Certifications",
      contact: "Contact",
    },

    // Hero Section
    hero: {
      greeting: "Hi, I'm",
      role1: "Senior Frontend Developer",
      role2: "Computer Science Engineer",
      role3: "Angular Expert",
      role4: "React Specialist",
      description:
        "Computer Science Engineer crafting exceptional user experiences with Angular and React for over 5 years. Transforming ideas into interactive, responsive web applications.",
      years: "Years Exp",
      projects: "Projects",
      dedication: "Dedication",
      getInTouch: "Get In Touch",
      viewWork: "View My Work",
    },

    // About Section
    about: {
      title: "About Me",
      subtitle: "Passionate about creating digital experiences",
      journeyTitle: "My Journey",
      paragraphs: [
        "As a Computer Engineering graduate with over 5 years of experience, I've dedicated my career to mastering the art of frontend development.",
        "My expertise spans across Angular and React ecosystems, where I've built scalable, responsive applications that serve thousands of users daily.",
        "Currently working at WCS and GlobalResources, I continue to push the boundaries of what's possible in web development.",
      ],
      coffee: "Fueled by coffee",
      passion: "Powered by passion",
      values: [
        { title: "Clean Code", description: "Writing maintainable, scalable code following SOLID principles", icon: Code2 },
        { title: "Team Player", description: "Collaborating effectively in agile environments with cross-functional teams", icon: Users },
        { title: "Goal Oriented", description: "Focused on delivering high-quality solutions that exceed expectations", icon: Target, },
        { title: "Innovation", description: "Always exploring new technologies and best practices in development", icon: Lightbulb, },
      ],
      quickFactsTitle: "Quick Facts",
      quickFacts: [
        { title: "Angular", label: "Primary Framework" },
        { title: "React", label: "Secondary Expertise" },
        { title: "Full Stack", label: "Development Approach" },
        { title: "Agile", label: "Methodology Expert" },
      ],
    },

    // Skills Section
    skills: {
      title: "Technical Skills",
      subtitle: "A comprehensive toolkit built through years of hands-on experience and continuous learning",
      frontend: "Frontend Development",
      backend: "Backend Development",
      database: "Database & Tools",
      softSkills: "Soft Skills & Methodologies",
      continuousLearning: "Continuous Learning",
      learningDescription:
        "Committed to staying current with the latest technologies and best practices through continuous education and certification.",
      platziCerts: "Multiple Platzi Certifications",
      softSkillsList: [
        "Problem Solving",
        "Team Leadership",
        "Code Review",
        "Agile/Scrum",
        "Communication",
        "Mentoring",
        "Project Management",
        "Technical Writing",
      ],
    },

    // Experience Section
    experience: {
      title: "Work",
      titleHighlight: "Experience",
      subtitle: "A journey of growth, learning, and delivering exceptional results across diverse projects and teams",
      current: "Current",
      responsibilities: "Key Responsibilities",
      achievements: "Key Achievements",
      technologies: "Technologies Used",
      freelance: "Freelance",
      projects: "Projects",
      highlights: "Career Highlights",
      yearsExp: "Years Experience",
      companies: "Companies",
      satisfaction: "Client Satisfaction",
      items: [
        {
          id: 1,
          company: "GlobalResources",
          position: "Frontend Developer",
          type: "Full Time",
          period: "Mar 2024 - Present",
          location: "Remote",
          current: true,
          description: [
            "Specialized in React development for modern web applications",
            "Collaborated with international teams on scalable frontend solutions",
            "Implemented responsive designs and optimized user experiences",
            "Participated in agile development processes and sprint planning",
          ],
          technologies: ["React", "TypeScript", "JavaScript", "CSS3", "HTML5", "Git"],
          achievements: [
            "Successfully delivered multiple React-based projects",
            "Improved application performance through optimization techniques",
          ],
        },
        {
          id: 2,
          company: "WCS (Sistemas Webconsult Colombia)",
          position: "Full Stack Developer",
          type: "Full Time",
          period: "Oct 2023 - Present",
          location: "Colombia",
          current: true,
          description: [
            "Implemented interactive and responsive user interfaces using Angular and React with Next.js",
            "Designed and developed reusable components to improve efficiency and consistency in frontend development",
            "Guaranteed code quality through implementation of good development practices and code reviews",
            "Collaborated closely with designers, project managers and developers in agile environments",
            "Provided ongoing support for applications, resolving bugs and improving functionality",
          ],
          technologies: [
            "Angular",
            "React",
            "Next.js",
            "TypeScript",
            "C#",
            ".NET",
            "Node.js",
            "Express.js",
            "NestJS",
            "MongoDB",
            "SQL",
            "Tailwind CSS",
            "Bootstrap",
          ],
          achievements: [
            "Led frontend architecture decisions for multiple projects",
            "Improved code quality through comprehensive review processes",
            "Mentored junior developers in best practices",
          ],
        },
        {
          id: 3,
          company: "Jirka IT Solutions",
          position: "Frontend Developer",
          type: "Full Time",
          period: "Jul 2022 - Aug 2023",
          location: "Colombia · Remote",
          current: false,
          description: [
            "Converted design prototypes into high-quality user interfaces using Angular",
            "Built consistent components with Angular Material, ngPrime and PrimeFlex",
            "Ensured responsive and adaptive layouts across devices and resolutions",
            "Implemented advanced UI features such as interactive forms and dynamic tables",
            "Applied performance optimizations to improve load times and runtime performance",
          ],
          technologies: [
            "Angular",
            "Angular Material",
            "ngPrime",
            "PrimeFlex",
            "TypeScript",
            "HTML5",
            "CSS3",
            "Responsive Design",
          ],
          achievements: [
            "Delivered pixel-perfect interfaces aligned with design systems",
            "Improved responsiveness and cross-device compatibility",
          ],
        },
        {
          id: 4,
          company: "DisaService",
          position: "Frontend Developer",
          type: "Full Time",
          period: "Jun 2021 - Jun 2023",
          location: "Colombia",
          current: false,
          description: [
            "Designed and developed attractive and functional user interfaces using Angular as the main framework",
            "Successfully integrated services and backend APIs into user interfaces using Angular best practices",
            "Diagnosed and solved technical problems and errors in the frontend",
            "Actively contributed to team meetings and code review sessions",
            "Focused on creating intuitive user experiences that improved customer satisfaction",
          ],
          technologies: [
            "Angular",
            "TypeScript",
            "JavaScript",
            "HTML5",
            "CSS3",
            "SASS",
            "Bootstrap",
            "PrimeNG",
            "Angular Material",
            "CSS Grid",
            "Flexbox",
          ],
          achievements: [
            "Improved customer satisfaction through intuitive UI design",
            "Established best practices for API integration",
            "Contributed to team knowledge sharing and collaboration",
          ],
        },
      ],
      freelanceProjects: [
        {
          name: "AP Building Maintenance",
          url: "#",
          period: "Jun 2023",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
        {
          name: "VieraFloors",
          url: "#",
          period: "Sep 2021",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
        {
          name: "Dexter-Price",
          url: "#",
          period: "Nov 2021",
          description: "Website focused on selling coloring books for children",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
      ],
    },

    // Certifications Section
    certifications: {
      title: "Certifications",
      learning: "Learning",
      subtitle:
        "Committed to continuous learning and professional development through comprehensive certification programs",
      certificationsCount: "Certifications",
      platform: "Primary Platform",
      advanced: "Advanced",
      skillLevel: "Skill Level",
      period: "Learning Period",
      allCerts: "All Certifications",
      frontend: "Frontend",
      backend: "Backend",
      tools: "Tools",
      skillsCovered: "Skills Covered",
      viewCert: "View Certificate",
      philosophy: "Continuous Learning Philosophy",
      philosophyText:
        "In the rapidly evolving world of technology, staying current isn't just an advantage—it's essential. My commitment to continuous learning through platforms like Platzi ensures I'm always equipped with the latest skills and best practices to deliver exceptional results.",
      viewAll: "View All Certificates",
      items: [
        {
          id: "apis-net",
          title: "APIs with .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2983-apis-net/diploma/detalle/",
          date: "2023",
          description: "Design and implement RESTful APIs using .NET, covering routing, controllers, and best practices.",
          category: "backend",
          level: "Advanced",
          color: "from-green-500 to-green-600",
          skills: ["REST APIs", ".NET", "ASP.NET Core", "Controllers", "Routing", "Middleware", "Authentication"],
        },
        {
          id: "fundamentos-net",
          title: "Fundamentals of .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2883-fundamentos-net/diploma/detalle/",
          date: "2023",
          description: "Core concepts of .NET and C# for building reliable backend services.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["C#", ".NET Core", "OOP", "CLR", "NuGet", "Console Apps"],
        },
        {
          id: "entity-framework",
          title: "Entity Framework Fundamentals",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2987-entity-framework/diploma/detalle/",
          date: "2023",
          description: "Data modeling and persistence patterns using Entity Framework for relational databases.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["Entity Framework", "ORM", "Migrations", "LINQ", "Data Modeling", "DbContext"],
        },
        {
          id: "linq",
          title: "Data Handling in C# with LINQ",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4263-linq/diploma/detalle/",
          date: "2023",
          description: "Querying and manipulating collections and data sources effectively with LINQ.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["LINQ", "Collections", "IEnumerable", "Query Syntax", "Lambda Expressions"],
        },
        {
          id: "solid-csharp",
          title: "SOLID Principles in C# and .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4761-solid-csharp-net/diploma/detalle/",
          date: "2023",
          description: "Applying SOLID principles to write maintainable and testable C# code.",
          category: "backend",
          level: "Advanced",
          color: "from-blue-500 to-blue-600",
          skills: ["SOLID", "SRP", "OCP", "LSP", "ISP", "DIP", "Design Principles"],
        },
        {
          id: "clean-code-csharp",
          title: "Clean Code and Best Practices in C#",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4788-clean-code-csharp/diploma/detalle/",
          date: "2023",
          description: "Clean code techniques and best practices for C# development.",
          category: "tools",
          level: "Advanced",
          color: "from-gray-600 to-gray-700",
          skills: ["Clean Code", "Refactoring", "Naming", "Unit Testing", "Best Practices"],
        },
        {
          id: "bootstrap4",
          title: "Bootstrap 4",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1331-bootstrap/diploma/detalle/",
          date: "2022",
          description: "Responsive UI building blocks and utilities with Bootstrap 4.",
          category: "frontend",
          level: "Intermediate",
          color: "from-purple-500 to-purple-600",
          skills: ["Bootstrap", "Responsive Design", "Grid System", "Components", "Utilities"],
        },
        {
          id: "angular-avanzado",
          title: "Angular Advanced",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11919-angular-avanzado/diploma/detalle/",
          date: "2023",
          description: "Advanced Angular techniques: performance, architecture and large-scale app patterns.",
          category: "frontend",
          level: "Advanced",
          color: "from-red-600 to-red-700",
          skills: ["Angular", "Performance", "Architecture", "Lazy Loading", "Change Detection"],
        },
        {
          id: "angular-basico",
          title: "Angular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/8352-angular/diploma/detalle/",
          date: "2022",
          description: "Core Angular concepts: components, modules, data binding and services.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Components", "Services", "Data Binding", "Modules"],
        },
        {
          id: "angular-trello",
          title: "Angular + Trello Project",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4461-angular-trello/diploma/detalle/",
          date: "2022",
          description: "Build a Trello-like app using Angular and real-time interactions.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-500 to-red-600",
          skills: ["Angular", "Components", "State", "Drag & Drop", "UI"],
        },
        {
          id: "angular-tailwind",
          title: "Angular with Tailwind",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4459-angular-tailwind/diploma/detalle/",
          date: "2022",
          description: "Integrate Tailwind CSS into Angular projects for utility-first styling.",
          category: "frontend",
          level: "Intermediate",
          color: "from-teal-400 to-teal-600",
          skills: ["Angular", "Tailwind CSS", "Styling", "Responsive Design"],
        },
        {
          id: "angular-autenticacion",
          title: "Angular Authentication",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4460-angular-autenticacion/diploma/detalle/",
          date: "2022",
          description: "Implement authentication flows and guards in Angular applications.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-500 to-red-600",
          skills: ["Angular", "Auth", "JWT", "Guards", "Security"],
        },
        {
          id: "angular-forms",
          title: "Angular Forms",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2027-angular-forms/diploma/detalle/",
          date: "2022",
          description: "Reactive and template-driven forms in Angular with validation patterns.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Reactive Forms", "Validation", "Form Controls"],
        },
        {
          id: "angular-modular",
          title: "Angular Modular Architecture",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2487-angular-modular/diploma/detalle/",
          date: "2022",
          description: "Module-based architecture and feature modules for scalable Angular apps.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Modules", "Lazy Loading", "Architecture"],
        },
        {
          id: "angular-apis",
          title: "Angular + APIs",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2495-angular-apis/diploma/detalle/",
          date: "2022",
          description: "Consume REST APIs in Angular using HttpClient and best practices.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "HttpClient", "APIs", "Services"],
        },
        {
          id: "angular-componentes",
          title: "Angular Components",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2486-angular-componentes/diploma/detalle/",
          date: "2022",
          description: "Deep dive into building reusable components in Angular.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Components", "Inputs/Outputs", "ViewChild"],
        },
        {
          id: "angular16",
          title: "Angular 16",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2478-angular16/diploma/detalle/",
          date: "2023",
          description: "Updates and features introduced in Angular 16.",
          category: "frontend",
          level: "Intermediate",
          color: "from-red-500 to-red-600",
          skills: ["Angular 16", "New Features", "Signals", "Optimizations"],
        },
        {
          id: "react-avanzado",
          title: "React Advanced",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11223-react-avanzado/diploma/detalle/",
          date: "2023",
          description: "Advanced React patterns, performance and architecture.",
          category: "frontend",
          level: "Advanced",
          color: "from-blue-600 to-blue-700",
          skills: ["React", "Performance", "Patterns", "Advanced Hooks"],
        },
        {
          id: "react-testing-library",
          title: "React Testing Library",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11224-react-testing-library/diploma/detalle/",
          date: "2023",
          description: "Testing components with React Testing Library and best practices.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-500 to-blue-600",
          skills: ["Testing", "RTL", "Jest", "Unit Tests"],
        },
        {
          id: "react-ssr",
          title: "React SSR",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/6241-react-ssr/diploma/detalle/",
          date: "2022",
          description: "Server-side rendering patterns for React applications.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-500 to-blue-600",
          skills: ["SSR", "React", "Rendering", "Next.js"],
        },
        {
          id: "react-redux",
          title: "React Redux Professional",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3219-react-redux-profesional/diploma/detalle/",
          date: "2021",
          description: "State management in React with Redux and best practices.",
          category: "frontend",
          level: "Advanced",
          color: "from-blue-500 to-blue-600",
          skills: ["Redux", "State Management", "React", "Middleware"],
        },
        {
          id: "react-typescript",
          title: "React + TypeScript",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/5481-react-typescript/diploma/detalle/",
          date: "2022",
          description: "Using TypeScript with React for safer, scalable codebases.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-500 to-blue-600",
          skills: ["React", "TypeScript", "Props", "Generics"],
        },
        {
          id: "react-state-machines",
          title: "React State Machines",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3108-react-state-machines/diploma/detalle/",
          date: "2021",
          description: "Modeling UI behavior with state machines in React.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-400 to-blue-500",
          skills: ["State Machines", "XState", "React"],
        },
        {
          id: "react-router",
          title: "React Router",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3468-react-router/diploma/detalle/",
          date: "2021",
          description: "Client-side routing patterns with React Router.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-400 to-blue-500",
          skills: ["React Router", "Routing", "Navigation"],
        },
        {
          id: "reactjs-intro",
          title: "React.js",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11887-reactjs/diploma/detalle/",
          date: "2020",
          description: "Introductory React course covering fundamentals and component-based UI.",
          category: "frontend",
          level: "Beginner",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "Components", "JSX"],
        },
        {
          id: "laboratorio-react",
          title: "React Lab",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7397-laboratorio-react/diploma/detalle/",
          date: "2021",
          description: "Hands-on React projects and exercises.",
          category: "frontend",
          level: "Intermediate",
          color: "from-blue-400 to-blue-600",
          skills: ["React", "Projects", "Practice"],
        },
        {
          id: "react-vite-tailwind",
          title: "React + Vite + Tailwind",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7396-react-vite-tailwindcss/diploma/detalle/",
          date: "2022",
          description: "Scaffold React apps with Vite and style with Tailwind CSS.",
          category: "tools",
          level: "Intermediate",
          color: "from-teal-400 to-teal-600",
          skills: ["Vite", "Tailwind CSS", "React", "Tooling"],
        },
        {
          id: "react-basico",
          title: "React Basics",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7395-react/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Core React concepts and component-driven development.",
          category: "frontend",
          level: "Beginner",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "JSX", "Components"],
        },
        {
          id: "npm-js",
          title: "npm & JS",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1763-npm-js/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Package management and npm workflows for JavaScript projects.",
          category: "tools",
          level: "Intermediate",
          color: "from-gray-400 to-gray-600",
          skills: ["npm", "Packages", "Publishing", "Scripts"],
        },
        {
          id: "typescript-22",
          title: "TypeScript 2.2",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2878-typescript-22/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "TypeScript fundamentals and modern typing features.",
          category: "tools",
          level: "Intermediate",
          color: "from-blue-500 to-blue-600",
          skills: ["TypeScript", "Types", "Generics"],
        },
        {
          id: "react-2019",
          title: "React (2019)",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1548-react-2019/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Legacy React course covering patterns from 2019 era.",
          category: "frontend",
          level: "Beginner",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "Components"],
        },
        {
          id: "frontend-developer",
          title: "Frontend Developer",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2467-frontend-developer/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Comprehensive frontend developer path covering web fundamentals.",
          category: "frontend",
          level: "Advanced",
          color: "from-primary to-accent",
          skills: ["HTML5", "CSS3", "JavaScript", "Frameworks", "Tooling"],
        },
      ],
    },

    // Contact Section
    contact: {
      title: "Let's Connect",
      subtitle:
        "Ready to bring your next project to life? Let's discuss how we can work together to create something amazing.",
      getInTouch: "Get In Touch",
      description:
        "I'm always interested in new opportunities, challenging projects, and collaborating with talented teams. Whether you have a project in mind or just want to say hello, feel free to reach out!",
      location: "Location",
      quickConnect: "Quick Connect",
      sendEmail: "Send Email",
      linkedinMessage: "LinkedIn Message",
      viewGithub: "View GitHub",
      emailLabel: "Email",
      githubLabel: "GitHub",
      linkedinLabel: "LinkedIn",
      readyTitle: "Ready to Start Your Project?",
      readyDescription:
        "Let's turn your ideas into reality. With over 5 years of experience in frontend development, I'm ready to help you build something extraordinary.",
      startConversation: "Start a Conversation",
      viewMyWork: "View My Work",
    },
  },
  es: {
    // Navigation
    nav: {
      home: "Inicio",
      about: "Acerca de",
      skills: "Habilidades",
      experience: "Experiencia",
      certifications: "Certificaciones",
      contact: "Contacto",
    },

    // Hero Section
    hero: {
      greeting: "Hola, soy",
      role1: "Desarrollador Frontend Senior",
      role2: "Ingeniero en Informática",
      role3: "Experto en Angular",
      role4: "Especialista en React",
      description:
        "Ingeniero en Informática creando experiencias de usuario excepcionales con Angular y React por más de 5 años. Transformando ideas en aplicaciones web interactivas y responsivas.",
      years: "Años Exp",
      projects: "Proyectos",
      dedication: "Dedicación",
      getInTouch: "Contáctame",
      viewWork: "Ver Mi Trabajo",
    },

    // About Section
    about: {
      title: "Acerca de Mí",
      subtitle: "Apasionado por crear experiencias digitales",
      journeyTitle: "Mi Trayectoria",
      paragraphs: [
        "Como graduado en Ingeniería Informática con más de 5 años de experiencia, he dedicado mi carrera a dominar el arte del desarrollo frontend.",
        "Mi experiencia abarca los ecosistemas de Angular y React, donde he construido aplicaciones escalables y responsivas que sirven a miles de usuarios diariamente.",
        "Actualmente trabajando en WCS y GlobalResources, continuo expandiendo los límites de lo posible en el desarrollo web.",
      ],
      coffee: "Impulsado por el café",
      passion: "Movido por la pasión",
      values: [
        { title: "Código Limpio", description: "Escribir código mantenible y escalable siguiendo principios SOLID", icon: Code2 },
        { title: "Trabajo en Equipo", description: "Colaborar eficazmente en entornos ágiles con equipos multifuncionales", icon: Users },
        { title: "Orientado a Metas", description: "Enfocado en entregar soluciones de alta calidad que superen expectativas", icon: Target },
        { title: "Innovación", description: "Siempre explorando nuevas tecnologías y mejores prácticas en desarrollo", icon: Lightbulb },
      ],
      quickFactsTitle: "Datos Rápidos",
      quickFacts: [
        { title: "Angular", label: "Framework Principal" },
        { title: "React", label: "Experiencia Secundaria" },
        { title: "Full Stack", label: "Enfoque de Desarrollo" },
        { title: "Agile", label: "Experto en Metodologías" },
      ],
    },

    // Skills Section
    skills: {
      title: "Habilidades Técnicas",
      subtitle:
        "Un conjunto completo de herramientas construido a través de años de experiencia práctica y aprendizaje continuo",
      frontend: "Desarrollo Frontend",
      backend: "Desarrollo Backend",
      database: "Base de Datos y Herramientas",
      softSkills: "Habilidades Blandas y Metodologías",
      continuousLearning: "Aprendizaje Continuo",
      learningDescription:
        "Comprometido con mantenerme actualizado con las últimas tecnologías y mejores prácticas a través de educación continua y certificación.",
      platziCerts: "Múltiples Certificaciones de Platzi",
      softSkillsList: [
        "Resolución de Problemas",
        "Liderazgo de Equipo",
        "Revisión de Código",
        "Ágil/Scrum",
        "Comunicación",
        "Mentoría",
        "Gestión de Proyectos",
        "Documentación Técnica",
      ],
    },

    // Experience Section
    experience: {
      title: "Experiencia",
      titleHighlight: "Laboral",
      subtitle:
        "Un viaje de crecimiento, aprendizaje y entrega de resultados excepcionales en diversos proyectos y equipos",
      current: "Actual",
      responsibilities: "Responsabilidades Clave",
      achievements: "Logros Clave",
      technologies: "Tecnologías Utilizadas",
      freelance: "Proyectos",
      projects: "Freelance",
      highlights: "Aspectos Destacados de la Carrera",
      yearsExp: "Años de Experiencia",
      companies: "Empresas",
      satisfaction: "Satisfacción del Cliente",
      items: [
        {
          id: 1,
          company: "GlobalResources",
          position: "Desarrollador Frontend",
          type: "Tiempo Completo",
          period: "Mar 2024 - Presente",
          location: "Remoto",
          current: true,
          description: [
            "Especializado en desarrollo React para aplicaciones web modernas",
            "Colaboré con equipos internacionales en soluciones frontend escalables",
            "Implementé diseños responsivos y optimicé experiencias de usuario",
            "Participé en procesos de desarrollo ágil y planificación de sprints",
          ],
          technologies: ["React", "TypeScript", "JavaScript", "CSS3", "HTML5", "Git"],
          achievements: [
            "Entregué exitosamente múltiples proyectos basados en React",
            "Mejoré el rendimiento de aplicaciones a través de técnicas de optimización",
          ],
        },
        {
          id: 2,
          company: "WCS (Sistemas Webconsult Colombia)",
          position: "Desarrollador Full Stack",
          type: "Tiempo Completo",
          period: "Oct 2023 - Presente",
          location: "Colombia",
          current: true,
          description: [
            "Implementé interfaces de usuario interactivas y responsivas usando Angular y React con Next.js",
            "Diseñé y desarrollé componentes reutilizables para mejorar la eficiencia y consistencia en el desarrollo frontend",
            "Garanticé la calidad del código mediante la implementación de buenas prácticas de desarrollo y revisiones de código",
            "Colaboré estrechamente con diseñadores, gerentes de proyecto y desarrolladores en entornos ágiles",
            "Proporcioné soporte continuo para aplicaciones, resolviendo errores y mejorando la funcionalidad",
          ],
          technologies: [
            "Angular",
            "React",
            "Next.js",
            "TypeScript",
            "C#",
            ".NET",
            "Node.js",
            "Express.js",
            "NestJS",
            "MongoDB",
            "SQL",
            "Tailwind CSS",
            "Bootstrap",
          ],
          achievements: [
            "Lideré decisiones de arquitectura frontend para múltiples proyectos",
            "Mejoré la calidad del código a través de procesos de revisión integrales",
            "Mentoré desarrolladores junior en mejores prácticas",
          ],
        },
        {
          id: 3,
          company: "Jirka IT Solutions",
          position: "Desarrollador Frontend",
          type: "Tiempo Completo",
          period: "Jul 2022 - Ago 2023",
          location: "Colombia · En remoto",
          current: false,
          description: [
            "Convertí prototipos de diseño en interfaces de usuario de alta calidad usando Angular",
            "Construí componentes consistentes con Angular Material, ngPrime y PrimeFlex",
            "Aseguré diseños responsivos y adaptativos en múltiples dispositivos y resoluciones",
            "Implementé funciones avanzadas de UI como formularios interactivos y tablas dinámicas",
            "Apliqué optimizaciones de rendimiento para mejorar tiempos de carga y rendimiento en tiempo de ejecución",
          ],
          technologies: [
            "Angular",
            "Angular Material",
            "ngPrime",
            "PrimeFlex",
            "TypeScript",
            "HTML5",
            "CSS3",
            "Responsive Design",
          ],
          achievements: [
            "Entregué interfaces pixel-perfect alineadas con sistemas de diseño",
            "Mejoré la compatibilidad y responsividad entre dispositivos",
          ],
        },
        {
          id: 4,
          company: "DisaService",
          position: "Desarrollador Frontend",
          type: "Tiempo Completo",
          period: "Jun 2021 - Jun 2023",
          location: "Colombia",
          current: false,
          description: [
            "Diseñé y desarrollé interfaces de usuario atractivas y funcionales usando Angular como framework principal",
            "Integré exitosamente servicios y APIs backend en interfaces de usuario usando mejores prácticas de Angular",
            "Diagnostiqué y resolví problemas técnicos y errores en el frontend",
            "Contribuí activamente en reuniones de equipo y sesiones de revisión de código",
            "Me enfoqué en crear experiencias de usuario intuitivas que mejoraron la satisfacción del cliente",
          ],
          technologies: [
            "Angular",
            "TypeScript",
            "JavaScript",
            "HTML5",
            "CSS3",
            "SASS",
            "Bootstrap",
            "PrimeNG",
            "Angular Material",
            "CSS Grid",
            "Flexbox",
          ],
          achievements: [
            "Mejoré la satisfacción del cliente a través de diseño de UI intuitivo",
            "Establecí mejores prácticas para integración de APIs",
            "Contribuí al intercambio de conocimientos y colaboración del equipo",
          ],
        },
      ],
      freelanceProjects: [
        {
          name: "AP Building Maintenance",
          url: "#",
          period: "Jun 2023",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
        {
          name: "VieraFloors",
          url: "#",
          period: "Sep 2021",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
        {
          name: "Dexter-Price",
          url: "#",
          period: "Nov 2021",
          description: "Sitio web enfocado en la venta de libros para colorear para niños",
          technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
        },
      ],
    },

    // Certifications Section
    certifications: {
      title: "Certificaciones",
      learning: "Aprendizaje",
      subtitle:
        "Comprometido con el aprendizaje continuo y el desarrollo profesional a través de programas de certificación integrales",
      certificationsCount: "Certificaciones",
      platform: "Plataforma Principal",
      advanced: "Avanzado",
      skillLevel: "Nivel de Habilidad",
      period: "Período de Aprendizaje",
      allCerts: "Todas las Certificaciones",
      frontend: "Frontend",
      backend: "Backend",
      tools: "Herramientas",
      skillsCovered: "Habilidades Cubiertas",
      viewCert: "Ver Certificado",
      philosophy: "Filosofía de Aprendizaje Continuo",
      philosophyText:
        "En el mundo de la tecnología en rápida evolución, mantenerse actualizado no es solo una ventaja, es esencial. Mi compromiso con el aprendizaje continuo a través de plataformas como Platzi me asegura estar siempre equipado con las últimas habilidades y mejores prácticas para entregar resultados excepcionales.",
      viewAll: "Ver Todos los Certificados",
      items: [
        {
          id: "apis-net",
          title: "APIs con .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2983-apis-net/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Diseño e implementación de APIs RESTful con .NET, incluyendo controladores y buenas prácticas.",
          category: "backend",
          level: "Advanced",
          color: "from-green-500 to-green-600",
          skills: ["APIs REST", ".NET", "ASP.NET Core", "Controladores", "Routing", "Middleware", "Autenticación"],
        },
        {
          id: "fundamentos-net",
          title: "Fundamentos de .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2883-fundamentos-net/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Conceptos centrales de .NET y C# para construir servicios backend confiables.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["C#", ".NET Core", "POO", "CLR", "NuGet", "Aplicaciones de consola"],
        },
        {
          id: "entity-framework",
          title: "Fundamentos de Entity Framework",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2987-entity-framework/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Modelado de datos y patrones de persistencia usando Entity Framework para bases de datos relacionales.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["Entity Framework", "ORM", "Migraciones", "LINQ", "Modelado de datos", "DbContext"],
        },
        {
          id: "linq",
          title: "Manejo de Datos en C# con LINQ",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4263-linq/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Consulta y manipulación de colecciones y orígenes de datos con LINQ de forma eficiente.",
          category: "backend",
          level: "Intermediate",
          color: "from-green-400 to-green-500",
          skills: ["LINQ", "Colecciones", "IEnumerable", "Sintaxis de consulta", "Expresiones lambda"],
        },
        {
          id: "solid-csharp",
          title: "Principios SOLID en C# y .NET",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4761-solid-csharp-net/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Aplicación de los principios SOLID para escribir código C# mantenible y testeable.",
          category: "backend",
          level: "Advanced",
          color: "from-blue-500 to-blue-600",
          skills: ["SOLID", "SRP", "OCP", "LSP", "ISP", "DIP", "Principios de diseño"],
        },
        {
          id: "clean-code-csharp",
          title: "Buenas Prácticas y Código Limpio en C#",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4788-clean-code-csharp/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Técnicas de código limpio y buenas prácticas para el desarrollo en C#.",
          category: "tools",
          level: "Advanced",
          color: "from-gray-600 to-gray-700",
          skills: ["Código limpio", "Refactorización", "Nombres", "Pruebas unitarias", "Buenas prácticas"],
        },
        {
          id: "bootstrap4",
          title: "Bootstrap 4",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1331-bootstrap/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Construcción de interfaces responsivas con utilidades y componentes de Bootstrap 4.",
          category: "frontend",
          level: "Intermediate",
          color: "from-purple-500 to-purple-600",
          skills: ["Bootstrap", "Diseño responsivo", "Sistema de grid", "Componentes", "Utilidades"],
        },
        {
          id: "angular-avanzado",
          title: "Angular Avanzado",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11919-angular-avanzado/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Técnicas avanzadas de Angular: rendimiento, arquitectura y patrones para aplicaciones a gran escala.",
          category: "frontend",
          level: "Avanzado",
          color: "from-red-600 to-red-700",
          skills: ["Angular", "Rendimiento", "Arquitectura", "Lazy Loading", "Change Detection"],
        },
        {
          id: "angular-basico",
          title: "Angular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/8352-angular/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Conceptos fundamentales de Angular: componentes, módulos, binding y servicios.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Componentes", "Servicios", "Data Binding", "Módulos"],
        },
        {
          id: "angular-trello",
          title: "Angular - Proyecto Trello",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4461-angular-trello/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Construcción de una aplicación tipo Trello utilizando Angular y características en tiempo real.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-500 to-red-600",
          skills: ["Angular", "Componentes", "Estado", "Drag & Drop", "UI"],
        },
        {
          id: "angular-tailwind",
          title: "Angular con Tailwind",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4459-angular-tailwind/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Integración de Tailwind CSS en proyectos Angular para un enfoque utility-first en estilos.",
          category: "frontend",
          level: "Intermedio",
          color: "from-teal-400 to-teal-600",
          skills: ["Angular", "Tailwind CSS", "Estilos", "Responsive"],
        },
        {
          id: "angular-autenticacion",
          title: "Autenticación en Angular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/4460-angular-autenticacion/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Implementación de flujos de autenticación y guards en aplicaciones Angular.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-500 to-red-600",
          skills: ["Angular", "Auth", "JWT", "Guards", "Seguridad"],
        },
        {
          id: "angular-forms",
          title: "Formularios en Angular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2027-angular-forms/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Formularios reactivos y template-driven en Angular con patrones de validación.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Reactive Forms", "Validación", "Form Controls"],
        },
        {
          id: "angular-modular",
          title: "Angular Modular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2487-angular-modular/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Arquitectura modular y feature modules para aplicaciones Angular escalables.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Módulos", "Lazy Loading", "Arquitectura"],
        },
        {
          id: "angular-apis",
          title: "Angular + APIs",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2495-angular-apis/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Consumo de APIs REST en Angular utilizando HttpClient y buenas prácticas.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "HttpClient", "APIs", "Servicios"],
        },
        {
          id: "angular-componentes",
          title: "Componentes en Angular",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2486-angular-componentes/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Profundización en la construcción de componentes reutilizables en Angular.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-400 to-red-500",
          skills: ["Angular", "Componentes", "Inputs/Outputs", "ViewChild"],
        },
        {
          id: "angular16",
          title: "Angular 16",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2478-angular16/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Novedades y características introducidas en Angular 16.",
          category: "frontend",
          level: "Intermedio",
          color: "from-red-500 to-red-600",
          skills: ["Angular 16", "Signals", "Optimización"],
        },
        {
          id: "react-avanzado",
          title: "React Avanzado",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11223-react-avanzado/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Patrones avanzados de React, rendimiento y arquitectura.",
          category: "frontend",
          level: "Avanzado",
          color: "from-blue-600 to-blue-700",
          skills: ["React", "Rendimiento", "Patrones", "Hooks avanzados"],
        },
        {
          id: "react-testing-library",
          title: "React Testing Library",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11224-react-testing-library/diploma/detalle/",
          year: "2023",
          date: "2023",
          description: "Pruebas de componentes con React Testing Library y mejores prácticas.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-500 to-blue-600",
          skills: ["Testing", "RTL", "Jest", "Pruebas unitarias"],
        },
        {
          id: "react-ssr",
          title: "React SSR",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/6241-react-ssr/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Patrones de renderizado del lado servidor para aplicaciones React.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-500 to-blue-600",
          skills: ["SSR", "React", "Rendering", "Next.js"],
        },
        {
          id: "react-redux",
          title: "React Redux Profesional",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3219-react-redux-profesional/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Gestión de estado en React con Redux y buenas prácticas.",
          category: "frontend",
          level: "Avanzado",
          color: "from-blue-500 to-blue-600",
          skills: ["Redux", "Gestión de estado", "React", "Middleware"],
        },
        {
          id: "react-typescript",
          title: "React + TypeScript",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/5481-react-typescript/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Uso de TypeScript con React para bases de código más seguras y escalables.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-500 to-blue-600",
          skills: ["React", "TypeScript", "Props", "Generics"],
        },
        {
          id: "react-state-machines",
          title: "Máquinas de Estado en React",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3108-react-state-machines/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Modelado del comportamiento de la UI con máquinas de estado en React.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-400 to-blue-500",
          skills: ["Máquinas de estado", "XState", "React"],
        },
        {
          id: "react-router",
          title: "React Router",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/3468-react-router/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Ruteo del lado cliente con React Router.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-400 to-blue-500",
          skills: ["React Router", "Ruteo", "Navegación"],
        },
        {
          id: "reactjs-intro",
          title: "React.js",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/11887-reactjs/diploma/detalle/",
          year: "2020",
          date: "2020",
          description: "Curso introductorio de React que cubre fundamentos y UI basada en componentes.",
          category: "frontend",
          level: "Principiante",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "Componentes", "JSX"],
        },
        {
          id: "laboratorio-react",
          title: "Laboratorio React",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7397-laboratorio-react/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Proyectos prácticos y ejercicios con React.",
          category: "frontend",
          level: "Intermedio",
          color: "from-blue-400 to-blue-600",
          skills: ["React", "Proyectos", "Práctica"],
        },
        {
          id: "react-vite-tailwind",
          title: "React + Vite + Tailwind",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7396-react-vite-tailwindcss/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Scaffold de aplicaciones React con Vite y estilos con Tailwind CSS.",
          category: "tools",
          level: "Intermedio",
          color: "from-teal-400 to-teal-600",
          skills: ["Vite", "Tailwind CSS", "React", "Tooling"],
        },
        {
          id: "react-basico",
          title: "React Básico",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/7395-react/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Conceptos fundamentales de React y desarrollo basado en componentes.",
          category: "frontend",
          level: "Principiante",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "JSX", "Componentes"],
        },
        {
          id: "npm-js",
          title: "npm & JS",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1763-npm-js/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Gestión de paquetes y flujos con npm en proyectos JavaScript.",
          category: "tools",
          level: "Intermedio",
          color: "from-gray-400 to-gray-600",
          skills: ["npm", "Paquetes", "Publicación", "Scripts"],
        },
        {
          id: "typescript-22",
          title: "TypeScript 2.2",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2878-typescript-22/diploma/detalle/",
          year: "2022",
          date: "2022",
          description: "Fundamentos de TypeScript y características modernas de tipado.",
          category: "tools",
          level: "Intermedio",
          color: "from-blue-500 to-blue-600",
          skills: ["TypeScript", "Tipos", "Generics"],
        },
        {
          id: "react-2019",
          title: "React (2019)",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/1548-react-2019/diploma/detalle/",
          year: "2019",
          date: "2019",
          description: "Curso de React con patrones de la época 2019.",
          category: "frontend",
          level: "Principiante",
          color: "from-blue-300 to-blue-500",
          skills: ["React", "Componentes"],
        },
        {
          id: "frontend-developer",
          title: "Frontend Developer",
          provider: "Platzi",
          url: "https://platzi.com/p/Chrisolivaresdev/curso/2467-frontend-developer/diploma/detalle/",
          year: "2021",
          date: "2021",
          description: "Ruta completa de frontend cubriendo fundamentos web.",
          category: "frontend",
          level: "Avanzado",
          color: "from-primary to-accent",
          skills: ["HTML5", "CSS3", "JavaScript", "Frameworks", "Tooling"],
        },
      ],
    },

    // Contact Section
    contact: {
      title: "Conectemos",
      subtitle:
        "¿Listo para dar vida a tu próximo proyecto? Hablemos sobre cómo podemos trabajar juntos para crear algo increíble.",
      getInTouch: "Ponte en Contacto",
      description:
        "Siempre estoy interesado en nuevas oportunidades, proyectos desafiantes y colaborar con equipos talentosos. Ya sea que tengas un proyecto en mente o solo quieras saludar, ¡no dudes en contactarme!",
      location: "Ubicación",
      quickConnect: "Conexión Rápida",
      sendEmail: "Enviar Email",
      linkedinMessage: "Mensaje LinkedIn",
      viewGithub: "Ver GitHub",
      emailLabel: "Email",
      githubLabel: "GitHub",
      linkedinLabel: "LinkedIn",
      readyTitle: "¿Listo para Comenzar tu Proyecto?",
      readyDescription:
        "Convirtamos tus ideas en realidad. Con más de 5 años de experiencia en desarrollo frontend, estoy listo para ayudarte a construir algo extraordinario.",
      startConversation: "Iniciar Conversación",
      viewMyWork: "Ver Mi Trabajo",
    },
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "es")) {
      setLanguage(savedLanguage)
    }
  }, [])
  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }, [])

  const t = useCallback((key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return value || key
  }, [language])

  const value = useMemo(
    () => ({ language, setLanguage: handleSetLanguage, t, translations: translations[language] }),
    [language, handleSetLanguage, t],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
